### ISSUE TITLE
Installation is broken & dependencies are out of date

### ISSUE THREAD

**Issue by acacio** [creationix/wheat#10]
install.sh was removed (in commit 5f9dd7f47a5a5f26c6aa).

Also, the dependency chain is out-of-date:

wheat depends on git, which depends on kiwi which has not been updated in a while (posix vs. fs, and still using promises).

I was trying to contribute a howtonode.org article and I find myself "yak shaving" ;-)

**Comment by Marak** [comment]
i have a working bundle of this for the nodejitsu blog, let me know if you need a copy, we'll be open sourcing the entire blog soon

**Comment by creationix** [comment]
It's installable with npm now. (the git module that depended on kiwi wasn't mine)
