### ISSUE TITLE
wrong version tags on http://howtonode.org/ 'other articles by this author'

### ISSUE THREAD

**Issue by mkroehnert** [creationix/wheat#2]
Hi,

going to http://howtonode.org/ brings up the main page and in the articles section some of article links show version tags and some don't.

Now if you select an article without version tag (for example the [control-flow](http://howtonode.org/control-flow) article) the links in the 'other articles by this author' section don't show any version tags at all.

But if you go to an article with version tag (for example the most recent [volcano-wheat](http://howtonode.org/volcano-wheat) article) all links in this section show the v0.1.91 version tag.

**Comment by creationix** [comment]
Thanks, I noticed this this morning, I'll fix it tomorrow. Resting today.

**Comment by creationix** [comment]
Fixed it!
