### ISSUE TITLE
wheat breaks if there is a hidden file in the howtonode.org articles directory

### ISSUE THREAD

**Issue by mkroehnert** [creationix/wheat#3]
Steps:
1. checkout the howtonode.org repository
2. create a hidden file in the howtonode.org/articles directory (eg howtonode.org/articles/.xyz)
3. start wheat in the howtonode.org directory

Now point the browser to the url wheat is serving the files on.
The result is not the expected website but an error message:

```
Error: No such file or directory
at node.js:748:9
```

Used versions:
- howtonode.org revision 1b741f6ac53
- wheat revision 1a143a90f780
- node.js version 0.1.91

**Comment by creationix** [comment]
should be good now in a00db37ce059ccc30069419f1036d16a6b2ca0a6

**Comment by mkroehnert** [comment]
Confirmed to work.

Thanks

**Comment by creationix** [comment]
Awesome, let me know if there are more problems.
