### ISSUE TITLE
git-fs 0.0.7 breaks wheat

### ISSUE THREAD

**Issue by CrypticSwarm** [creationix/wheat#32]
git-fs v0.0.7 breaks wheat.  It appears to be coming from a change in the Git.readFile having an optional format.  Currently when using git-fs v0.0.7 wheat will only spit out 404 pages.

**Comment by creationix** [comment]
I see the same thing.  I've had a hard time keep on top of my pull requests lately.  I think there is a pending pull request for wheat that fixes things on that end, but I can't seem to find it.

**Comment by CrypticSwarm** [comment]
fixed in version 0.2.3
