### ISSUE TITLE
submodule error

### ISSUE THREAD

**Issue by na** [creationix/wheat#4]
I get this error when ./install.sh

```
Loading dependencies as git submodules...
fatal: reference is not a tree: d9637b1da5029fe4a7a5a95761cf40381fef131b
Unable to checkout 'd9637b1da5029fe4a7a5a95761cf40381fef131b' in submodule path 'lib/wheat/connectpkg'
```

from http://www.kernel.org/pub/software/scm/git/docs/user-manual.html#submodules _Pitfalls with submodules_ it looks like a change to connectpkg has not been published yet.

**Comment by na** [comment]
I got it running by checking out the latest tag:
    git checkout v0.1.0
    ./install.sh

**Comment by creationix** [comment]
The tag was point to the wrong place, try again.

**Comment by garryyao** [comment]
The problem is still there with HEAD.

**Comment by TooTallNate** [comment]
I also just tried with a fresh `git clone` and got the same error...

I've forked and updated the commit refs in my fork: http://github.com/TooTallNate/wheat/commit/fd86660ea72c0f467b6c4dd467c08cc59dee2b06

**Comment by creationix** [comment]
Thanks TooTallNate, I just grabbed your code.  Does this fix it for everyone?

**Comment by TooTallNate** [comment]
I think maybe you forgot to push?

**Comment by markc** [comment]
@na thanks for the hint. The connectpkg submodule still points to the old repo in .gitmodules and when I change it to senchalabs/connect.git I get this error...

```
Loading dependencies as git submodules...
fatal: reference is not a tree: d9637b1da5029fe4a7a5a95761cf40381fef131b
Unable to checkout 'd9637b1da5029fe4a7a5a95761cf40381fef131b' in submodule path 'lib/wheat/connectpkg'
```

**Comment by creationix** [comment]
Wheat no longer uses submodules for dependencies, but is installable via npm.
