### ISSUE TITLE
no install.sh

### ISSUE THREAD

**Issue by Dieterbe** [creationix/wheat#6]
according to the readme, i should execute install.sh after cloning the wheat repo.
but there is no install.sh

**Comment by Marak** [comment]
no install.sh

no npm package

**Comment by easternbloc** [comment]
Agreed. It's http://github.com/creationix/wheat/tree/v0.1.0 but not in master.

**Comment by creationix** [comment]
I fixed the docs.  Install is via npm now.

**Comment by easternbloc** [comment]
Cool thanks.
